import type { DeploymentConfig } from "@/types/deployment";
import type { Agent } from "@/types/agent";
import { convertToOpenClaw } from "@/lib/agents/converter";

// Determine the host binding based on the deployment target.
function getHost(target: DeploymentConfig["target"]): string {
  if (target === "aws-lightsail") return "0.0.0.0";
  return "127.0.0.1";
}

// Build the docker-compose.yml content for the deployment.
function generateDockerCompose(config: DeploymentConfig): string {
  const host = getHost(config.target);
  const bindAddress = config.target === "aws-lightsail" ? "0.0.0.0" : "127.0.0.1";

  return `version: "3.8"

services:
  openclaw:
    image: openclaw/openclaw:latest
    container_name: ${config.name}
    ports:
      - "${bindAddress}:${config.gatewayPort}:${config.gatewayPort}"
      - "${bindAddress}:${config.dashboardPort}:${config.dashboardPort}"
    volumes:
      - ./openclaw.json:/app/openclaw.json:ro
      - ./workspaces:/app/workspaces
    environment:
      - OPENCLAW_GATEWAY_PORT=${config.gatewayPort}
      - OPENCLAW_GATEWAY_HOST=${host}
      - OPENCLAW_DASHBOARD_PORT=${config.dashboardPort}
    restart: unless-stopped
    env_file:
      - .env
`;
}

// Build the openclaw.json configuration file content.
function generateOpenClawConfig(config: DeploymentConfig): string {
  const host = getHost(config.target);

  const agents = config.agents.map((agent) => ({
    id: agent.slug,
    name: agent.customName || agent.name,
    workspace: `./workspaces/${agent.slug}`,
    model: agent.model || config.defaultModel,
  }));

  const openclawConfig = {
    gateway: {
      port: config.gatewayPort,
      host,
    },
    dashboard: {
      port: config.dashboardPort,
    },
    agents,
    sessions: {
      interAgentEnabled: config.interAgentEnabled,
    },
    defaultModel: config.defaultModel,
  };

  return JSON.stringify(openclawConfig, null, 2) + "\n";
}

// Build the startup.sh bash script content.
function generateStartupScript(config: DeploymentConfig): string {
  const host = getHost(config.target);
  const awsDockerCheck =
    config.target === "aws-lightsail"
      ? `
# Verify Docker is installed on this instance
if ! command -v docker &> /dev/null; then
  echo "Docker is not installed. Installing..."
  curl -fsSL https://get.docker.com | sh
  sudo usermod -aG docker \\$USER
  echo "Docker installed. You may need to log out and back in for group changes."
fi

if ! command -v docker compose &> /dev/null; then
  echo "Docker Compose plugin not found. Please install docker-compose-plugin."
  exit 1
fi
`
      : "";

  return `#!/usr/bin/env bash
set -euo pipefail

echo "============================================"
echo "  ${config.name}"
echo "  Target: ${config.target}"
echo "  Agents: ${config.agents.length}"
echo "============================================"
${awsDockerCheck}
echo "Starting services..."
docker compose up -d

echo ""
echo "Services are starting up."
echo "  Gateway:   http://${host}:${config.gatewayPort}"
echo "  Dashboard: http://${host}:${config.dashboardPort}"
echo ""
echo "Use 'docker compose logs -f' to follow logs."
echo "Use 'docker compose down' to stop all services."
`;
}

// Build the .env file content with placeholder values.
function generateEnvFile(config: DeploymentConfig): string {
  return `# ${config.name} Environment Configuration
# Generated by The Agency Configurator

OPENCLAW_GATEWAY_PORT=${config.gatewayPort}
OPENCLAW_DASHBOARD_PORT=${config.dashboardPort}
OPENCLAW_DEFAULT_MODEL=${config.defaultModel}
OPENCLAW_INTER_AGENT=${config.interAgentEnabled ? "true" : "false"}

# Add your API keys below
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
`;
}

// Build an auto-generated README.md quickstart guide.
function generateReadme(config: DeploymentConfig): string {
  const agentList = config.agents
    .map((a) => `- **${a.customName || a.name}** (\`${a.slug}\`)`)
    .join("\n");

  return `# ${config.name}

Deployment package generated by The Agency Configurator.

## Quick Start

1. Add your API keys to the \`.env\` file.
2. Run the startup script:

\`\`\`bash
chmod +x startup.sh
./startup.sh
\`\`\`

## Configuration

- **Target:** ${config.target}
- **Gateway Port:** ${config.gatewayPort}
- **Dashboard Port:** ${config.dashboardPort}
- **Default Model:** ${config.defaultModel}
- **Inter-Agent Communication:** ${config.interAgentEnabled ? "Enabled" : "Disabled"}

## Agents

${agentList}

## Files

| File | Description |
|------|-------------|
| \`docker-compose.yml\` | Docker service definitions |
| \`openclaw.json\` | OpenClaw runtime configuration |
| \`startup.sh\` | One-command startup script |
| \`.env\` | Environment variables and API keys |
| \`workspaces/\` | Agent workspace directories |

## Management

\`\`\`bash
# View logs
docker compose logs -f

# Stop services
docker compose down

# Restart services
docker compose restart
\`\`\`
`;
}

// Generate the full set of deployment files for the given configuration.
// Returns a map of relative file path to file content.
export function generateDeployment(
  config: DeploymentConfig,
  agents: Agent[]
): Record<string, string> {
  const files: Record<string, string> = {};

  // Core deployment files
  files["docker-compose.yml"] = generateDockerCompose(config);
  files["openclaw.json"] = generateOpenClawConfig(config);
  files["startup.sh"] = generateStartupScript(config);
  files[".env"] = generateEnvFile(config);
  files["README.md"] = generateReadme(config);

  // Generate workspace files for each agent in the deployment config
  for (const deployAgent of config.agents) {
    const agent = agents.find((a) => a.slug === deployAgent.slug);
    if (!agent) continue;

    const openClawFiles = convertToOpenClaw(agent);

    files[`workspaces/${deployAgent.slug}/SOUL.md`] = openClawFiles["SOUL.md"];
    files[`workspaces/${deployAgent.slug}/AGENTS.md`] = openClawFiles["AGENTS.md"];
    files[`workspaces/${deployAgent.slug}/IDENTITY.md`] = openClawFiles["IDENTITY.md"];
  }

  return files;
}
