import type {
  NexusPhase,
  AgentSession,
  Task,
  Handoff,
  MissionMetrics,
} from "@/types/nexus";

export const NEXUS_PHASES: NexusPhase[] = [
  {
    id: 0,
    name: "Intelligence & Discovery",
    shortName: "Discovery",
    description: "Validate opportunity before committing resources",
    status: "completed",
    agents: ["trend-researcher", "feedback-synthesizer", "ux-researcher"],
    gateStatus: "passed",
  },
  {
    id: 1,
    name: "Strategy & Architecture",
    shortName: "Strategy",
    description: "Define architecture and project plan",
    status: "completed",
    agents: ["studio-producer", "sprint-prioritizer", "ux-architect", "backend-architect"],
    gateStatus: "passed",
  },
  {
    id: 2,
    name: "Foundation & Scaffolding",
    shortName: "Foundation",
    description: "Set up CI/CD, scaffolding, and design system",
    status: "completed",
    agents: ["devops-automator", "frontend-developer", "backend-architect"],
    gateStatus: "passed",
  },
  {
    id: 3,
    name: "Build & Iterate",
    shortName: "Build",
    description: "Core development with Dev-QA loops",
    status: "active",
    agents: [
      "frontend-developer",
      "backend-architect",
      "ai-engineer",
      "evidence-collector",
      "content-creator",
      "growth-hacker",
    ],
    gateStatus: "pending",
  },
  {
    id: 4,
    name: "Quality & Hardening",
    shortName: "Harden",
    description: "Final integration testing and performance validation",
    status: "upcoming",
    agents: ["reality-checker", "performance-benchmarker", "api-tester"],
  },
  {
    id: 5,
    name: "Launch & Growth",
    shortName: "Launch",
    description: "Deploy to production and activate growth strategies",
    status: "upcoming",
    agents: ["growth-hacker", "content-creator", "devops-automator"],
  },
  {
    id: 6,
    name: "Operate & Evolve",
    shortName: "Operate",
    description: "Monitor, support, and iterate",
    status: "upcoming",
    agents: ["analytics-reporter", "infrastructure-maintainer", "support-responder"],
  },
];

export const MOCK_AGENTS: AgentSession[] = [
  {
    id: "sess-001",
    agentSlug: "frontend-developer",
    agentName: "Frontend Developer",
    agentEmoji: "\u{1F5A5}\uFE0F",
    division: "engineering",
    status: "active",
    currentTask: "Build dashboard component layout",
    phase: 3,
    lastActive: new Date(Date.now() - 30000).toISOString(),
    tasksCompleted: 12,
    firstPassRate: 0.83,
  },
  {
    id: "sess-002",
    agentSlug: "backend-architect",
    agentName: "Backend Architect",
    agentEmoji: "\u{1F3D7}\uFE0F",
    division: "engineering",
    status: "active",
    currentTask: "Implement REST API endpoints",
    phase: 3,
    lastActive: new Date(Date.now() - 60000).toISOString(),
    tasksCompleted: 9,
    firstPassRate: 0.89,
  },
  {
    id: "sess-003",
    agentSlug: "ai-engineer",
    agentName: "AI Engineer",
    agentEmoji: "\u{1F916}",
    division: "engineering",
    status: "active",
    currentTask: "Train recommendation model",
    phase: 3,
    lastActive: new Date(Date.now() - 120000).toISOString(),
    tasksCompleted: 5,
    firstPassRate: 0.80,
  },
  {
    id: "sess-004",
    agentSlug: "evidence-collector",
    agentName: "Evidence Collector",
    agentEmoji: "\u{1F50D}",
    division: "testing",
    status: "active",
    currentTask: "QA: Verify dashboard responsiveness",
    phase: 3,
    lastActive: new Date(Date.now() - 15000).toISOString(),
    tasksCompleted: 18,
    firstPassRate: 1.0,
  },
  {
    id: "sess-005",
    agentSlug: "devops-automator",
    agentName: "DevOps Automator",
    agentEmoji: "\u{2699}\uFE0F",
    division: "engineering",
    status: "idle",
    phase: 3,
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    tasksCompleted: 7,
    firstPassRate: 0.86,
  },
  {
    id: "sess-006",
    agentSlug: "ui-designer",
    agentName: "UI Designer",
    agentEmoji: "\u{1F3A8}",
    division: "design",
    status: "idle",
    phase: 3,
    lastActive: new Date(Date.now() - 1800000).toISOString(),
    tasksCompleted: 6,
    firstPassRate: 0.67,
  },
  {
    id: "sess-007",
    agentSlug: "content-creator",
    agentName: "Content Creator",
    agentEmoji: "\u270D\uFE0F",
    division: "marketing",
    status: "active",
    currentTask: "Write onboarding copy",
    phase: 3,
    lastActive: new Date(Date.now() - 45000).toISOString(),
    tasksCompleted: 4,
    firstPassRate: 0.75,
  },
  {
    id: "sess-008",
    agentSlug: "growth-hacker",
    agentName: "Growth Hacker",
    agentEmoji: "\u{1F4C8}",
    division: "marketing",
    status: "queued",
    phase: 3,
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    tasksCompleted: 2,
    firstPassRate: 1.0,
  },
  {
    id: "sess-009",
    agentSlug: "sprint-prioritizer",
    agentName: "Sprint Prioritizer",
    agentEmoji: "\u{1F4CB}",
    division: "product",
    status: "idle",
    phase: 3,
    lastActive: new Date(Date.now() - 5400000).toISOString(),
    tasksCompleted: 3,
    firstPassRate: 1.0,
  },
  {
    id: "sess-010",
    agentSlug: "security-engineer",
    agentName: "Security Engineer",
    agentEmoji: "\u{1F6E1}\uFE0F",
    division: "engineering",
    status: "error",
    currentTask: "Dependency vulnerability scan",
    phase: 3,
    lastActive: new Date(Date.now() - 900000).toISOString(),
    tasksCompleted: 1,
    firstPassRate: 0.5,
  },
  {
    id: "sess-011",
    agentSlug: "brand-guardian",
    agentName: "Brand Guardian",
    agentEmoji: "\u{1F451}",
    division: "design",
    status: "idle",
    phase: 3,
    lastActive: new Date(Date.now() - 4500000).toISOString(),
    tasksCompleted: 3,
    firstPassRate: 1.0,
  },
  {
    id: "sess-012",
    agentSlug: "analytics-reporter",
    agentName: "Analytics Reporter",
    agentEmoji: "\u{1F4CA}",
    division: "support",
    status: "idle",
    phase: 3,
    lastActive: new Date(Date.now() - 6000000).toISOString(),
    tasksCompleted: 2,
    firstPassRate: 1.0,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "TSK-001",
    title: "Build dashboard component layout",
    description: "Create responsive grid layout for the main dashboard",
    phase: 3,
    status: "in_progress",
    priority: "high",
    assignedAgent: "Frontend Developer",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "TSK-002",
    title: "Implement REST API endpoints",
    description: "Create CRUD endpoints for tasks and agents",
    phase: 3,
    status: "in_progress",
    priority: "high",
    assignedAgent: "Backend Architect",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: "TSK-003",
    title: "QA: Verify dashboard responsiveness",
    description: "Test dashboard across desktop, tablet, mobile viewports",
    phase: 3,
    status: "in_qa",
    priority: "medium",
    assignedAgent: "Frontend Developer",
    qaAgent: "Evidence Collector",
    retryCount: 1,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 15000).toISOString(),
  },
  {
    id: "TSK-004",
    title: "Train recommendation model",
    description: "Fine-tune content recommendation model on user data",
    phase: 3,
    status: "in_progress",
    priority: "high",
    assignedAgent: "AI Engineer",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "TSK-005",
    title: "Write onboarding copy",
    description: "Create welcome flow copy and tooltips",
    phase: 3,
    status: "in_progress",
    priority: "medium",
    assignedAgent: "Content Creator",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: "TSK-006",
    title: "Set up monitoring and alerting",
    description: "Configure Prometheus + Grafana for production monitoring",
    phase: 3,
    status: "passed",
    priority: "high",
    assignedAgent: "DevOps Automator",
    qaAgent: "Evidence Collector",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "TSK-007",
    title: "Design system token audit",
    description: "Verify all components use design system tokens consistently",
    phase: 3,
    status: "passed",
    priority: "medium",
    assignedAgent: "UI Designer",
    qaAgent: "Evidence Collector",
    retryCount: 1,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "TSK-008",
    title: "Dependency vulnerability scan",
    description: "Run full dependency audit and fix critical vulnerabilities",
    phase: 3,
    status: "failed",
    priority: "critical",
    assignedAgent: "Security Engineer",
    qaAgent: "Evidence Collector",
    retryCount: 2,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "TSK-009",
    title: "SEO meta tags implementation",
    description: "Add proper meta tags, OG images, and structured data",
    phase: 3,
    status: "backlog",
    priority: "low",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "TSK-010",
    title: "Growth acquisition strategy",
    description: "Define channels, CAC targets, and first-month growth plan",
    phase: 3,
    status: "backlog",
    priority: "medium",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "TSK-011",
    title: "Brand consistency review",
    description: "Audit all pages for brand guideline compliance",
    phase: 3,
    status: "blocked",
    priority: "medium",
    assignedAgent: "Brand Guardian",
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 4500000).toISOString(),
  },
];

export const MOCK_HANDOFFS: Handoff[] = [
  {
    id: "HO-001",
    fromAgent: "UX Architect",
    fromEmoji: "\u{1F4D0}",
    toAgent: "Frontend Developer",
    toEmoji: "\u{1F5A5}\uFE0F",
    phase: 3,
    priority: "high",
    context: "Component architecture and design system tokens ready for implementation",
    status: "completed",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    completedAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "HO-002",
    fromAgent: "Backend Architect",
    fromEmoji: "\u{1F3D7}\uFE0F",
    toAgent: "Frontend Developer",
    toEmoji: "\u{1F5A5}\uFE0F",
    phase: 3,
    priority: "high",
    context: "API endpoints documented and deployed to staging. OpenAPI spec available.",
    status: "completed",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    completedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "HO-003",
    fromAgent: "Frontend Developer",
    fromEmoji: "\u{1F5A5}\uFE0F",
    toAgent: "Evidence Collector",
    toEmoji: "\u{1F50D}",
    phase: 3,
    priority: "medium",
    context: "Dashboard layout complete. Ready for QA: responsive design, accessibility, cross-browser.",
    status: "accepted",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "HO-004",
    fromAgent: "Evidence Collector",
    fromEmoji: "\u{1F50D}",
    toAgent: "Frontend Developer",
    toEmoji: "\u{1F5A5}\uFE0F",
    phase: 3,
    priority: "medium",
    context: "QA FAIL (attempt 1/3): Mobile viewport has overflow issues on task cards. Desktop passes.",
    status: "completed",
    createdAt: new Date(Date.now() - 72000000).toISOString(),
    completedAt: new Date(Date.now() - 60000000).toISOString(),
  },
  {
    id: "HO-005",
    fromAgent: "Content Creator",
    fromEmoji: "\u270D\uFE0F",
    toAgent: "Brand Guardian",
    toEmoji: "\u{1F451}",
    phase: 3,
    priority: "low",
    context: "Onboarding copy draft ready for brand voice review.",
    status: "pending",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "HO-006",
    fromAgent: "AI Engineer",
    fromEmoji: "\u{1F916}",
    toAgent: "Backend Architect",
    toEmoji: "\u{1F3D7}\uFE0F",
    phase: 3,
    priority: "high",
    context: "Model training complete. Need API endpoint for inference serving.",
    status: "pending",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const MOCK_METRICS: MissionMetrics = {
  activeAgents: 5,
  totalAgents: 12,
  currentPhase: 3,
  phaseName: "Build & Iterate",
  tasksInProgress: 4,
  tasksCompleted: 2,
  totalTasks: 11,
  estimatedCost: 47.82,
  firstPassRate: 0.82,
  avgRetries: 0.45,
};
